=== woundeddonkey/cityofadelaide/src/schemas/person-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "description": "Details of a passenger or crew member that traveled on the City of Adelaide ship",
  "type": "object",
  "properties": {
    "first_name": {
      "type": "string",
      "description": "First name of the person"
    },
    "middle_names": {
      "type": ["string", "null"],
      "description": "Middle name(s) of the person"
    },
    "last_name": {
      "type": "string",
      "description": "Last name of the person"
    },
    "gender": {
      "type": ["string", "null"],
      "description": "Gender of the person, can be Male, Female or Null if unknown",
      "enum": ["Male", "Female", null]
    },
    "birth_date": {
      "type": ["string", "null"],
      "format": "date",
      "description": "Date the person was born (YYYY-MM-DD format)"
    },
    "birth_place": {
      "type": ["string", "null"],
      "description": "Place of birth for the person"
    },
    "death_date": {
      "type": ["string", "null"],
      "format": "date",
      "description": "Date the person died (YYYY-MM-DD format)"
    },
    "death_place": {
      "type": ["string", "null"],
      "description": "Location the person died"
    },
    "age_at_death": {
      "type": ["string", "null"],
      "description": "Age of the person at death"
    },
    "burial_place": {
      "type": ["string", "null"],
      "description": "Place the person was buried"
    }
  },
  "required": ["first_name", "last_name"]
}

=== woundeddonkey/cityofadelaide/documents/Frame/Frame.json
[
  {
    "first_name": "James",
    "middle_names": null,
    "last_name": "Frame",
    "gender": "Male",
    "birth_date": "1848-09-24",
    "birth_place": "Lanark, South Lanarkshire, Scotland",
    "death_date": "1906-01-25",
    "death_place": "Kookynie, Menzies Shire, Western Australia",
    "age_at_death": "57 years",
    "burial_place": "Kookynie Cemetery"
  }
]

=== woundeddonkey/cityofadelaide/documents/Baker/Family Tree of Bridget Baker.json
[
  {
    "first_name": "Bridget",
    "middle_names": null,
    "last_name": "Baker",
    "gender": "Female",
    "birth_date": "1855-01-01",
    "birth_place": null,
    "death_date": null,
    "death_place": null,
    "age_at_death": null,
    "burial_place": null
  },
  {
    "first_name": "John",
    "middle_names": null,
    "last_name": "Green/e",
    "gender": "Male",
    "birth_date": "1845-01-01",
    "birth_place": null,
    "death_date": "1909-01-01",
    "death_place": null,
    "age_at_death": "64 years",
    "burial_place": null
  },
  {
    "first_name": "Cecelia",
    "middle_names": null,
    "last_name": "Green",
    "gender": "Female",
    "birth_date": "1878-01-01",
    "birth_place": null,
    "death_date": null,
    "death_place": null,
    "age_at_death": null,
    "burial_place": null
  },
  {
    "first_name": "Thomas",
    "middle_names": null,
    "last_name": "Green",
    "gender": "Male",
    "birth_date": "1880-01-01",
    "birth_place": null,
    "death_date": "1909-01-01",
    "death_place": null,
    "age_at_death": "29 years",
    "burial_place": null
  },
  {
    "first_name": "Mary Teresa",
    "middle_names": null,
    "last_name": "Green",
    "gender": "Female",
    "birth_date": "1880-01-01",
    "birth_place": null,
    "death_date": "1942-01-01",
    "death_place": null,
    "age_at_death": "62 years",
    "burial_place": null
  },
  {
    "first_name": "Harrold James",
    "middle_names": null,
    "last_name": "Keightley",
    "gender": "Male",
    "birth_date": "1879-01-01",
    "birth_place": null,
    "death_date": "1943-01-01",
    "death_place": null,
    "age_at_death": "64 years",
    "burial_place": null
  },
  {
    "first_name": "Maude Wilson",
    "middle_names": null,
    "last_name": "Keightley",
    "gender": "Female",
    "birth_date": "1907-01-01",
    "birth_place": null,
    "death_date": "1988-01-01",
    "death_place": null,
    "age_at_death": "81 years",
    "burial_place": null
  },
  {
    "first_name": "Leonard Charles",
    "middle_names": null,
    "last_name": "Kimber",
    "gender": "Male",
    "birth_date": "1909-01-01",
    "birth_place": null,
    "death_date": "1975-01-01",
    "death_place": null,
    "age_at_death": "66 years",
    "burial_place": null
  },
  {
    "first_name": "Samuel Clifford",
    "middle_names": null,
    "last_name": "Keightley",
    "gender": "Male",
    "birth_date": "1908-01-01",
    "birth_place": null,
    "death_date": "1981-01-01",
    "death_place": null,
    "age_at_death": "73 years",
    "burial_place": null
  },
  {
    "first_name": "Marjorie Ada",
    "middle_names": null,
    "last_name": "Bradshaw",
    "gender": "Female",
    "birth_date": "1910-01-01",
    "birth_place": null,
    "death_date": null,
    "death_place": null,
    "age_at_death": null,
    "burial_place": null
  },
  {
    "first_name": "Thomas",
    "middle_names": "Reg Reginald",
    "last_name": "Keightley",
    "gender": "Male",
    "birth_date": "1909-01-01",
    "birth_place": null,
    "death_date": "1987-01-01",
    "death_place": null,
    "age_at_death": "78 years",
    "burial_place": null
  },
  {
    "first_name": "Dorothy Caroline",
    "middle_names": null,
    "last_name": "Banks",
    "gender": "Female",
    "birth_date": "1911-01-01",
    "birth_place": null,
    "death_date": "1990-01-01",
    "death_place": null,
    "age_at_death": "79 years",
    "burial_place": null
  },
  {
    "first_name": "Un-named",
    "middle_names": null,
    "last_name": "Green",
    "gender": null,
    "birth_date": "1883-01-01",
    "birth_place": null,
    "death_date": "1909-01-01",
    "death_place": null,
    "age_at_death": "26 years",
    "burial_place": null
  },
  {
    "first_name": "Elizabeth",
    "middle_names": null,
    "last_name": "Green",
    "gender": "Female",
    "birth_date": "1886-01-01",
    "birth_place": null,
    "death_date": "1909-01-01",
    "death_place": null,
    "age_at_death": "23 years",
    "burial_place": null
  },
  {
    "first_name": "Martin Francis",
    "middle_names": null,
    "last_name": "Green",
    "gender": "Male",
    "birth_date": "1888-01-01",
    "birth_place": null,
    "death_date": "1918-01-01",
    "death_place": null,
    "age_at_death": "30 years",
    "burial_place": null
  },
  {
    "first_name": "Annie",
    "middle_names": null,
    "last_name": "Green",
    "gender": "Female",
    "birth_date": "1890-01-01",
    "birth_place": null,
    "death_date": "1891-01-01",
    "death_place": null,
    "age_at_death": "1 year",
    "burial_place": null
  }
]

=== woundeddonkey/cityofadelaide/documents/_Tests/MultiplePersons.json
[
  {
    "first_name": "James",
    "middle_names": null,
    "last_name": "Smith",
    "gender": "Male",
    "birth_date": "1850-01-01",
    "birth_place": "London, England",
    "death_date": "1920-05-15",
    "death_place": "Adelaide, Australia",
    "age_at_death": "70 years",
    "burial_place": "Adelaide Cemetery"
  },
  {
    "first_name": "Sarah",
    "middle_names": "Jane",
    "last_name": "Smith",
    "gender": "Female",
    "birth_date": "1855-03-12",
    "birth_place": "Liverpool, England",
    "death_date": "1925-08-20",
    "death_place": "Adelaide, Australia",
    "age_at_death": "70 years",
    "burial_place": "Adelaide Cemetery"
  },
  {
    "first_name": "William",
    "middle_names": "Henry",
    "last_name": "Smith",
    "gender": "Male",
    "birth_date": "1880-11-05",
    "birth_place": "At sea, aboard City of Adelaide",
    "death_date": "1950-02-10",
    "death_place": "Melbourne, Australia",
    "age_at_death": "69 years",
    "burial_place": "Melbourne Cemetery"
  }
]

=== woundeddonkey/cityofadelaide/documents/Fahy/Fahy.json
[
  {
    "first_name": "John",
    "middle_names": "William",
    "last_name": "Smith",
    "gender": "Male",
    "birth_date": "1850-03-15",
    "birth_place": "London, England",
    "death_date": "1920-11-23",
    "death_place": "Adelaide, Australia",
    "age_at_death": "70 years",
    "burial_place": "Adelaide Cemetery"
  }
]

=== woundeddonkey/cityofadelaide/documents/Cheadle/Alfred Stanley Cheadle.json
[
  {
    "first_name": "Alfred",
    "middle_names": "Stanley",
    "last_name": "Cheadle",
    "gender": "Male",
    "birth_date": "1853-06-15",
    "birth_place": "Halifax, Metropolitan Borough of Calderdale, West Yorkshire, England",
    "death_date": "1923-01-05",
    "death_place": "Victor Harbor, South Australia",
    "age_at_death": "69 years",
    "burial_place": "Saint Judes Cemetery, Brighton, South Australia"
  },
  {
    "first_name": "Margaret",
    "last_name": "Loutit",
    "gender": "Female",
    "birth_date": "1865-01-14",
    "birth_place": "Gawler, South Australia",
    "death_date": "1946-07-29",
    "death_place": "North Adelaide, South Australia",
    "age_at_death": "81 years",
    "burial_place": "Saint Judes Cemetery, Brighton, South Australia"
  },
  {
    "first_name": "Thomas",
    "middle_names": "Stanley",
    "last_name": "Cheadle",
    "gender": "Male",
    "birth_date": "1887-07-12",
    "birth_place": "East Adelaide, South Australia",
    "death_date": "1959-01-22",
    "death_place": "Adelaide, South Australia",
    "age_at_death": "71 years",
    "burial_place": "Centennial Park Cemetery, East Area, Rose Bed, N8, position 040"
  },
  {
    "first_name": "Norah",
    "middle_names": "Rivoli",
    "last_name": "Murphy",
    "gender": "Female",
    "birth_date": "1898-12-03",
    "birth_place": "Beachport, South Australia",
    "death_date": "1962-01-04",
    "death_place": "North Adelaide, South Australia",
    "age_at_death": "63 years",
    "burial_place": "Centennial Park Cemetery, East Area, Rose Bed, N8, position 041"
  },
  {
    "first_name": "Agnes",
    "last_name": "Cheadle",
    "gender": "Female",
    "birth_date": "1891-02-22",
    "birth_place": "East Adelaide, South Australia",
    "death_date": "1973-01-01",
    "death_place": "Kyneton, Victoria",
    "age_at_death": "81 years",
    "burial_place": "Macedon Cemetery"
  },
  {
    "first_name": "James",
    "middle_names": "Hugh Paterson",
    "last_name": "Davis",
    "gender": "Male",
    "birth_date": "1880-08-16",
    "birth_place": "Magill, South Australia",
    "death_date": "1967-10-31",
    "death_place": "Gisborne, Victoria",
    "age_at_death": "87 years",
    "burial_place": "Macedon Cemetery"
  },
  {
    "first_name": "Mary",
    "middle_names": "Alison",
    "last_name": "Cheadle",
    "gender": "Female",
    "birth_date": "1896-12-27",
    "birth_place": "Glenelg, South Australia",
    "death_date": "1983-03-15",
    "death_place": "Adelaide, South Australia",
    "age_at_death": "86 years",
    "burial_place": "Brighton Cemetery"
  },
  {
    "first_name": "Jefferson",
    "middle_names": "Hirst",
    "last_name": "Walker",
    "gender": "Male",
    "birth_date": "1901-07-16",
    "birth_place": "Hawthorn, Victoria",
    "death_date": "1941-11-27",
    "death_place": "Tobruk",
    "age_at_death": "40 years",
    "burial_place": "Plymouth Naval Memorial, Plymouth, Devon, England"
  },
  {
    "first_name": "Frances",
    "middle_names": "Margaret",
    "last_name": "Cheadle",
    "gender": "Female",
    "birth_date": "1900-05-20",
    "birth_place": "Glenelg, South Australia",
    "death_date": "1995-08-14",
    "death_place": "Adelaide, South Australia",
    "age_at_death": "95 years",
    "burial_place": "Brighton Cemetery"
  },
  {
    "first_name": "Dominic",
    "middle_names": "Mary Paul",
    "last_name": "McGuire",
    "gender": "Male",
    "birth_date": "1903-04-03",
    "birth_place": "Peterborough, South Australia",
    "death_date": "1978-06-15",
    "death_place": "Adelaide, South Australia",
    "age_at_death": "75 years",
    "burial_place": "Brighton Cemetery"
  },
  {
    "first_name": "Peter",
    "middle_names": "Roland",
    "last_name": "Cheadle",
    "gender": "Male",
    "birth_date": "1906-09-09",
    "birth_place": "Glenelg, South Australia",
    "death_date": "1985-03-31",
    "death_place": "South Australia",
    "age_at_death": "78 years",
    "burial_place": "Enfield Memorial Park Cemetery, RC, CGV, site 8"
  },
  {
    "first_name": "Jessie",
    "last_name": "Stodart",
    "gender": "Female",
    "birth_date": "1902-01-01",
    "birth_place": "Parkside, South Australia",
    "death_date": "1997-10-30",
    "death_place": "Walkerville, South Australia",
    "age_at_death": "95 years",
    "burial_place": "Enfield Memorial Park Cemetery, RC, CGV, site 8"
  }
]
